---
- name: Assert create new file module
  hosts: localhost
  collections:
    - netology.newfile
  tasks:
    - name: New file
      netology.newfile.new_file:
        path: ./another_file.txt
        content: "Another content"